AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Testing

Globals:
  Function:
    Timeout: 30



Resources:
  InputFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InputFunction
      CodeUri: input/
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
              - 's3:*'
              Resource: 'arn:aws:s3:::*/*'
      Layers:
      - !Ref SharedFiles
      Events:
        getDocumentSettings:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /documentSetting
            Method: GET
        postDocumentSetting:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /documentSetting
            Method: POST
        getDocumentSetting:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /documentSetting/{identifier}
            Method: GET
        updateDocumentSetting:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /documentSetting/{identifier}
            Method: PUT


        getDocuments:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /document
            Method: GET
        postDocument:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /document
            Method: POST
        getDocument:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /document/{identifier}
            Method: GET
        updateDocument:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /document/{identifier}
            Method: PUT

        getPageByAddress:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /page/{address}
            Method: GET
        updatePageByAddress:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /page/{address}
            Method: PUT

        updatePageBackground:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /page/{address}/background
            Method: PUT

  RecogniserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: RecogniserFunction
      CodeUri: recogniser/
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      Layers:
      - !Ref SharedFiles


  SharedFiles:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: SharedFiles
        Description: Shared files like models.py
        ContentUri: shared_files/
        CompatibleRuntimes:
            - python2.7
        RetentionPolicy: Retain


  ProfileApiGateway:
    DependsOn: InputFunction
    Type: 'AWS::Serverless::Api'
    ApiKeySourceType: HEADER
    Properties:
      StageName: Prod
      DefinitionUri: 'swagger.yaml'
      Variables:
        InputArn: !GetAtt InputFunction.Arn
      BinaryMediaTypes:
        - "image/jpeg"
        - "image/jpg"
        - "image/png"

  ApiKey: 
    DependsOn: ProfileApiGateway
    Type: AWS::ApiGateway::ApiKey
    Properties: 
      Name: "Test customer"
      Description: "CloudFormation API Key V1"
      Enabled: true
      GenerateDistinctId: false
  ApiUsagePlan:
    Type: "AWS::ApiGateway::UsagePlan"
    Properties:
      Description: Free usage plan
      Quota:
        Limit: 100
        Period: DAY
      Throttle:
        BurstLimit: 3
        RateLimit: 3
      UsagePlanName: Free
  ApiUsagePlanKey:
    Type: "AWS::ApiGateway::UsagePlanKey"
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan
