AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Testing

Globals:
  Function:
    Timeout: 30



Resources:
  InputFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InputFunction
      CodeUri: input/
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      Layers:
      - !Ref SharedFiles
      Events:
        getDocuments:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /document/
            Method: GET
        postDocument:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /document
            Method: POST
        getDocument:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /document/{identifier}
            Method: GET
        updateDocument:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /document/{identifier}
            Method: PUT

        updatePageBackground:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApiGateway
            Path: /page/{address}/background
            Method: PUT

  RecogniserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: RecogniserFunction
      CodeUri: recogniser/
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      Layers:
      - !Ref SharedFiles


  SharedFiles:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: SharedFiles
        Description: Shared files like models.py
        ContentUri: shared_files/
        CompatibleRuntimes:
            - python2.7
        RetentionPolicy: Retain


  ProfileApiGateway:
    DependsOn: InputFunction
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      DefinitionUri: 'swagger.yaml'
      Variables:
        InputArn: !GetAtt InputFunction.Arn
